### ISSUE TITLE
请教下你的服务端怎么是gradle，怎么玩的呢，是用的android studio来编译的么

### ISSUE THREAD

**Issue by dotcool** [baidao/tinker-manager#12]
麻烦了

**Comment by typ0520** [comment]
是用gradle构建的  如果想做定制 下载一个IntelliJ IDEA(和android studio差不多)开发，如果只是想用起来直接拿war包部署就行了   war放在了根目录/war下面，看里面的readme按步骤操作就可以跑起来了
