### ISSUE TITLE
注册报尼玛，出错了~系统异常

### ISSUE THREAD

**Issue by Aniderr** [baidao/tinker-manager#16]
请问如何解决？

**Comment by Aniderr** [comment]
检查tomcat 127.0.0.1是否能够通 能就没有问题 不能就将配置中的127.0.0.1改为localhost

**Comment by typ0520** [comment]
改成localhost就行了？

**Comment by Aniderr** [comment]
要看你电脑tomcat的访问路径是不是localhost 如果是就行 另外 我没有配置成功客户端的接入，tinker的配置不太会。

**Comment by typ0520** [comment]
你先把tinker自己的sample工程跑通，然后在按照文档接入server就加一个初始化和一个查询，另外在回报的server里面调用上报补丁应用结果的api，下周一会发布debug工具，支持扫描二维码调试补丁

**Comment by typ0520** [comment]
配置文件下周我把127.0.0.1都改成localhost

**Comment by Aniderr** [comment]
我删除了你sample build中的部分配置文件  然后跑起来了项目  还没细细看tinker的配置 之前单独照着配置没有通
