### ISSUE TITLE
另外我还想问问，如果tinker开始收费了，对这个有影响吗？

### ISSUE THREAD

**Issue by Aniderr** [baidao/tinker-manager#18]

**Comment by jp1017** [comment]
tinker收费？

**Comment by Aniderr** [comment]
对啊 tinker现在内测期免费 但是应该公测完之后会像阿里一样收费的吧

**Comment by jp1017** [comment]
这么悲催啊。。。收费了这个肯定受影响啊

**Comment by Aniderr** [comment]
所以啊 一直在纠结用什么能不受影响 难道真的要自己写？

**Comment by typ0520** [comment]
tinker不可能收费的，都开源出来了，开源协议限制着呢；收费的是tinkerpatch.com这个云服务，别把tinker和tinkerpatch.com搞混淆了

**Comment by jp1017** [comment]
> tinker不可能收费的，都开源出来了，开源协议限制着呢；收费的是tinkerpatch.com这个云服务，别把tinker和tinkerpatch.com搞混淆了

👍 谢谢，哈哈

**Comment by Aniderr** [comment]
额 这样啊 那他们的区别是什么呢？如果tinker就用需要的功能了，他的patch如何收费呢？

**Comment by jp1017** [comment]
> 额 这样啊 那他们的区别是什么呢？如果tinker就用需要的功能了，他的patch如何收费呢？

tinker是热补丁方案，serve是服务端，服务端需要用到云空间，所以他们要收费，服务端我们完全可以自己架设，这个库就是为此而生，如果我没说错的话 😄

**Comment by Aniderr** [comment]
额 好的 了解了 谢谢 我主要是在客户端接入上遇到点问题

**Comment by typ0520** [comment]
@jp1017 就是你理解的这样
