### ISSUE TITLE
Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:you must install tinker before get tinker sInstance

### ISSUE THREAD

**Issue by Aniderr** [baidao/tinker-manager#20]
在客户端配置tinker的时候，我已经增加了

classpath "com.tencent.tinker:tinker-patch-gradle-plugin:${TINKER_VERSION}"
compile("com.tencent.tinker:tinker-android-lib:${TINKER_VERSION}") { changing = true }
provided("com.tencent.tinker:tinker-android-anno:${TINKER_VERSION}") { changing = true }

这个配置，但是还是提示我要install， 请问如何解决？

**Comment by jp1017** [comment]
@Aniderr 这个问题不属于这里 :disappointed: 

把 `TINKER_VERSION` 改成具体版本号吧, 比如最新的1.7.5
