### ISSUE TITLE
[Question] 补丁包查询下发

### ISSUE THREAD

**Issue by zhenghuanpeng1992** [baidao/tinker-manager#25]
eg: 两个渠道 A B 分别打了补丁 patch A B. 版本号相同。
现在 发了补丁 patch A, 现在运行 B 渠道的 apk 仍会 `PatchManager.getInstance().queryAndApplyPatch` 下载到 A 渠道的 patch A。
目前没有通过 tinkerId 来查询下发？

**Comment by zhenghuanpeng1992** [comment]
渠道 A B 基准包的 tinkerId 不同， 用的 git sha.

**Comment by typ0520** [comment]
多渠道你是用productFlavors做的吧，目前不支持这种场景，建议使用美团的多渠道打包方案，所有的渠道的包代码都一样就不会出现为每个渠道单独打补丁的事情了，这样管理起来也方便；这个项目是想做一个通用的解决方案，没有和具体热修复方案绑定死，所以不会去做'通过 tinkerId 来查询下发'这类的事情

**Comment by zhenghuanpeng1992** [comment]
@typ0520 我就是使用渠道信息写在 apk 文件的 zip comment 中的方式。但是有时需要打某些渠道的首发包时就可能修改代码造成这个渠道的代码不同，那么 tinkerId 就不同了但是版本号一致。

**Comment by typ0520** [comment]
@zhenghuanpeng1992  举个例子来说，你需要发布了一个1.0.0的版本这个时候只发布了某几个渠道，过了几天你又想发另外几个渠道但是中间代码有变动过是这样吗；如果是这样不建议这样做，建议同一个版本发出去的所有渠道的包代码保持一致，这样方便管理，我们自己的工程也是这样管理的，即使想改动代码也是通过下发补丁，几乎所有的补丁管理平台都是按应用版本来下发补丁的
