### ISSUE TITLE
patchsdk中v4包的依赖

### ISSUE THREAD

**Issue by weinierfei** [baidao/tinker-manager#26]
patchsdk中依赖了24.0.0的v4包,如果我的项目中出现其他版本的时候,就会有冲突;尝试排除patchsdk中的v4依赖,不知道24.0.0跟24.2.0有啥不一样的;排除以后竟然找不到通知相关的类了;能不能再下个版本发布的时候,给v4提供provided,让引用着自己在工程中compile对应的v4包?

**Comment by typ0520** [comment]
@weinierfei 试下1.1.1这个版本，已经改好了
