### ISSUE TITLE
mac下报系统异常

### ISSUE THREAD

**Issue by liaoyizhe** [baidao/tinker-manager#35]
作者你好，按照安装步骤安装server，注册账号时候发现系统异常。在看tomcat日志时发现是mysql的连接异常。我在想会不会是配置文件没导入呢?
![image](https://user-images.githubusercontent.com/26520817/29813543-f2463116-8cdc-11e7-8dee-2f6a14dd9d04.png)

**Comment by typ0520** [comment]
这两个配置文件中的数据库连接配置都需要修改下

- hotfix-api.properties 
- hotfix-console.properties
