### ISSUE TITLE
升级到AS3.0 Gradle4.1出现异常

### ISSUE THREAD

**Issue by zhq991** [baidao/tinker-manager#41]
Error:(8, 42) 错误: 程序包com.tencent.tinker.commons.resutil不存在
Error:(9, 42) 错误: 程序包com.tencent.tinker.commons.ziputil不存在
Error:(10, 42) 错误: 程序包com.tencent.tinker.commons.ziputil不存在
Error:(11, 42) 错误: 程序包com.tencent.tinker.commons.ziputil不存在

在包里好像没看到相关的类

**Comment by typ0520** [comment]
tinker相关的请移步[https://github.com/Tencent/tinker](https://github.com/Tencent/tinker)

**Comment by zhq991** [comment]
是tinker升级了原因，是吧。

**Comment by zhq991** [comment]
示例里面引用还有些问题，tinker把ziputil 的包单独出来了，resutil去掉了。

**Comment by typ0520** [comment]
tinker-manager的sample中的内容有点老了，可以看tinker的sample，把初始化还有一些回调的地方的代码加上去就可以了

**Comment by zhq991** [comment]
好的，谢谢！是看里面写法有点不一样。添您麻烦了！
