### ISSUE TITLE
新增版本号格式不正确

### ISSUE THREAD

**Issue by Warpath** [baidao/tinker-manager#43]
新增APP版本号时出现如下提示
 ![](http://ofaiczjx6.bkt.clouddn.com/WX20171229-110349@2x.png)，希望能支持此种格式

**Comment by typ0520** [comment]
升级下后台，这个问题已经解决了

**Comment by Warpath** [comment]
后台已经是使用的最新的1.2.7，升级怎么升级呢

**Comment by Warpath** [comment]
修改了app.vm的正则可以使用了
