### ISSUE TITLE
补丁管理后台无法删除已有应用

### ISSUE THREAD

**Issue by YummyLau** [baidao/tinker-manager#44]
跑了下tinker-manger，发现新建的应用无法删除，是否是我操作有误，请教下。

**Comment by weinierfei** [comment]
是的,没做这个功能;正常建好了就不会删除(测试阶段除外);不过可以直接删除数据库数据

**Comment by YummyLau** [comment]
嗯嗯，感谢回复。
想问下，客户端代码里面get请求去查询补丁的时候，返回data实体内，downloadUrl的值总返回http://localhost:xxx/xxxx，localhost我已经在hotfix-console.properties修改过patch-static-url，且localhost已换成真实的项目服务器地址ip，然而客户端还是返回localhost。是需要调整哪些的配置文件吗？

**Comment by weinierfei** [comment]
修改完了后要重新run;然后重新上传新包;已上传的包的下载链是不会再变的

**Comment by YummyLau** [comment]
嗯嗯好的，明白。感谢回复

**Comment by YummyLau** [comment]
追加一个问题，tinker1.9.2版本，我成功从服务端拿下补丁，在DefaultPatchListener#patchCheck方法中，在代码66行中，ShareTinkerInternals.isTinkerEnableWithSharefPreferences中补丁校验不过无法修复。

**Comment by YummyLau** [comment]
readme的版本太久，升级新版本就可以了。

**Comment by YummyLau** [comment]
请教一下。关于同个版本打多次补丁，每个补丁的id用于对应基础包。可是后面的补丁覆盖前面的补丁时基于基础包覆盖的，比如A 修复 基础包 ，而希望后续的B 修复基础包，那么B要覆盖A，tinker需要哪些字段区分吗？ 我看到sample有个patchVersion，这个其作用吗？

**Comment by YummyLau** [comment]
在UpgradePatch类中我看代码之后的理解是。tinker每次加载都会根据tinkerid去找应用数据里的补丁包，如果补丁包存在，加载。如果当前加载了补丁之后，下载了新补丁，则会校验新旧补丁是否一致。用的是versionName来处理，而versionName则是以md5的前8位决定。这可以理解为，实际上不需要设置任何补丁的版本吗？只要两个不同文件，tinker则会用新的补丁覆盖旧的补丁。由于经验有限，所以请教下自己的理解是否正确。

**Comment by YummyLau** [comment]
补充一下，上面的表述不太正确。是默认补丁的名称以md5前8位凭接，是patchName而不是versionName。versionName是以md5全部字符串
