### ISSUE TITLE
系统异常,SQLException: Access denied for user 'root'@'localhost' (using password: YES)         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963) config 文件 

### ISSUE THREAD

**Issue by xiemuyou** [baidao/tinker-manager#45]

**Comment by xiemuyou** [comment]
![config](https://user-images.githubusercontent.com/12929443/37957083-a4fc7f5c-31df-11e8-8460-2708076e0c40.png)
请问我这样把配置文件我跟tomcat同级是正确的吗?
一直报
SQLException: Access denied for user 'root'@'localhost' (using password: YES) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
的错误,好像跟配置文件没有关联起来!

**Comment by typ0520** [comment]
配置文件放的不对，hotfix-apis.properties和hotfix-console.properties需要在d://opt/config下面

**Comment by xiemuyou** [comment]
hotfix-apis.properties和hotfix-console.properties
是在opt/config 文件下的,

**Comment by xiemuyou** [comment]
之前理解为跟tomcat同级,
改后好了,谢谢
