### ISSUE TITLE
war包的云盘链接好像坏了

### ISSUE THREAD

**Issue by GilfoyleTao** [baidao/tinker-manager#52]

**Comment by typ0520** [comment]
刚试了一下没问题啊， 你用这个链接试下
链接: https://pan.baidu.com/s/1EKKytXCyxnPVtWrAVjgWqQ 提取码: 58cw

**Comment by GilfoyleTao** [comment]
谢谢谢谢大佬！！！祝大佬生活愉快身体健康bug清零
