### ISSUE TITLE
能不能加一个渠道号管理

### ISSUE THREAD

**Issue by swung20cui** [baidao/tinker-manager#8]
比如googleplay不允许下发代码，如果直接在后台可能过滤掉就不用再客户端做特殊处理了

**Comment by typ0520** [comment]
有加这个的打算，我们自己用的时候有些加固的渠道无法应用patch不太好解决，目前是在客户端忽略掉了这个渠道，这样做不太好以后就没法控制了，如果能在控制台做配置比较灵活一些

**Comment by swung20cui** [comment]
OK，这个功能大概什么时候能做出来

**Comment by typ0520** [comment]
下周可以做好
